# Sentiment Analysis dengan PyCaret

Tujuan:
- Membandingkan beberapa algoritma machine learning
- Memilih model terbaik untuk klasifikasi sentimen
- Menyimpan model untuk deployment

## 1. Import Library

In [2]:
import pandas as pd
from pycaret.classification import *

## 2. Load Dataset Hasil Preprocessing

In [3]:
data = pd.read_csv('../data/ml_reviews_ready.csv')
data.head()

                                          clean_text sentiment
0  turun rating bintang nya tolong laku cheat rw ...   negatif
1  game nya baru enak enak main rank reset dibiar...   negatif
2  kondisi lag game banget jumpa cheat bug barusa...   negatif
3  montonnnnn gimana sih gak kali pas tengahtenga...    netral
4  kasih skin kalah musuh kasih musuh musuh berat...   negatif

## 3. Cek Missing Value

In [4]:
data.isnull().sum()
# Kalau ada nilai kosong:
data = data.dropna()

## 4. Setup PyCaret

In [5]:
clf = setup(
    data=data,
    target='sentiment',
    text_features=['clean_text'],
    session_id=42,
    train_size=0.8,
    fold=5,
    verbose=False
)

## 5. Benchmark 3 Model

In [6]:
lr = create_model('lr')
nb = create_model('nb')
rf = create_model('rf')

## 6. Bandingkan Semua Model

In [7]:
best_model = compare_models(include=['lr', 'nb', 'rf'])

Processing:   0%|          | 0/17 [00:00<?, ?it/s]

## 7.Evaluasi Model Terbaik

In [8]:
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

## 8. Prediksi pada Data Baru

In [9]:
new_data = pd.DataFrame({
    'clean_text': [
        'game nya seru banget dan skin nya keren',
        'server sering lag dan banyak bug setelah update'
    ]
})

hasil_prediksi = predict_model(best_model, data=new_data)
hasil_prediksi

,clean_text,prediction_label,prediction_score
0,game nya seru banget dan skin nya keren,positif,0.9406
1,server sering lag dan banyak bug setelah update,negatif,0.7472

## 9. Simpan Model Terbaik

In [10]:
save_model(best_model, '../app/best_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None, include=[],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('...
                  TransformerWrapper(exclude=None, include=['clean_text'],
                                     transformer=EmbedTextFeatures(kwargs=None,
                                                                   method='tf-idf'))),
                 ('trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=42,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False))],
          verbose=False),
 '../app/best_model.pkl')